image: docker:latest

variables:
  REPOSITORY_URL: 167732392816.dkr.ecr.us-east-1.amazonaws.com/bilbo
  ECS_SERVICE: webapp
  ECS_SERVICE_SIDEKIQ: sidekiq
  AWS_REGION: us-east-1
  DOCKER_IMAGE_CI: $REPOSITORY_URL:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}

services:
- docker:dind

before_script:
  - apk add --no-cache curl jq py-pip
  - pip install awscli ecs-deploy

stages:
  - build
  - test
  - deploy

build:
  script:
    - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    - docker pull $REPOSITORY_URL:latest || true
    #- docker build --cache-from $REPOSITORY_URL:latest -t $DOCKER_IMAGE_CI --build-arg CI_AGENT="${CI_AGENT}" .
    - docker build --cache-from $REPOSITORY_URL:latest -t $DOCKER_IMAGE_CI --build-arg CI_AGENT="${CI_AGENT}" --build-arg ENVNAME="production" --build-arg PAYPAL_USERNAME="$PAYPAL_USERNAME" --build-arg PAYPAL_PASSWORD="$PAYPAL_PASSWORD" --build-arg PAYPAL_SIGNATURE="$PAYPAL_SIGNATURE" --build-arg MAPS_API_KEY="$MAPS_API_KEY"  .
    - docker tag $DOCKER_IMAGE_CI ${REPOSITORY_URL}:latest
    - docker push $DOCKER_IMAGE_CI
    - docker push ${REPOSITORY_URL}:latest

  only:
    - master
    - staging
  tags:
    - docker

test:
  script:
    - docker-compose up -d --build --force-recreate
    - bash bilbo path
    - bilbo create-db
    - bilbo test
  only:
    - master
    - staging

deploy:
  script:
    - sh ecs-deploy.sh
  only:
    - master
    - staging
  tags:
    - docker
