image: docker:latest

variables:
  REPOSITORY_URL: 167732392816.dkr.ecr.us-east-1.amazonaws.com/bilbo
  ECS_SERVICE: webapp
  ECS_SERVICE_SIDEKIQ: sidekiq
  AWS_REGION: us-east-1
  DOCKER_IMAGE_CI: $REPOSITORY_URL:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  COMPOSE_INTERACTIVE_NO_CLI: 1
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext bash
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - pip install awscli ecs-deploy docker-compose

stages:
  - build_and_test
  - deploy

build_and_test:
  stage: build_and_test
  script:
    - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    - docker pull $REPOSITORY_URL:latest || true
    #- docker build --cache-from $REPOSITORY_URL:latest -t $DOCKER_IMAGE_CI --build-arg CI_AGENT="${CI_AGENT}" .
    - docker build --cache-from $REPOSITORY_URL:latest -t $DOCKER_IMAGE_CI --build-arg CI_AGENT="${CI_AGENT}" --build-arg ENVNAME="production" --build-arg PAYPAL_USERNAME="$PAYPAL_USERNAME" --build-arg PAYPAL_PASSWORD="$PAYPAL_PASSWORD" --build-arg PAYPAL_SIGNATURE="$PAYPAL_SIGNATURE" --build-arg MAPS_API_KEY="$MAPS_API_KEY"  .
    - docker tag $DOCKER_IMAGE_CI ${REPOSITORY_URL}:latest
    - docker-compose -f docker-compose-cicd.yml up -d
    - docker-compose exec -T app rails db:create
    - docker-compose exec -T app rails db:migrate
    - docker-compose exec -T app rails test -f
    - docker push $DOCKER_IMAGE_CI
    - docker push ${REPOSITORY_URL}:latest
  tags:
    - docker
  only:
    - master
    - staging

deploy:
  stage: deploy
  script:
    - sh ecs-deploy.sh
  only:
    - master
    - staging
  tags:
    - docker
  only:
    - master
    - staging
