image: docker:latest

variables:
  ECS_SERVICE: webapp
  ECS_SERVICE_SIDEKIQ: sidekiq
  AWS_REGION: us-east-1
  REPOSITORY_ID: 696716568292
  COMPOSE_INTERACTIVE_NO_CLI: 1
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
  - env
  - docker info
  - apk update
  - apk upgrade
  - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext bash
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - pip install 'cryptography==3.1.1'
  - pip install awscli ecs-deploy docker-compose

stages:
  - build_and_test
  - deploy

build_and_test:
  stage: build_and_test
  script:
    - bash -x cicd/build-test.sh
  tags:
    - docker
  only:
    - tags
  except:
    - branches

deploy:
  stage: deploy
  script:
    - bash -x cicd/ecs-deploy.sh
  tags:
    - docker
  only:
    - tags
  except:
    - branches
