version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass

  app:
    image: 696716568292.dkr.ecr.us-east-1.amazonaws.com/bilbo:latest
    command: web
    volumes:
      - .:/home/bilbo/app
    env_file:
      - .env
    depends_on:
      - db

  sidekiq:
    image: 696716568292.dkr.ecr.us-east-1.amazonaws.com/bilbo:latest
    command: sidekiq
    depends_on:
      - redis
      - db
      - app
    volumes:
      - .:/home/bilbo/app
    env_file:
      - .env

  redis:
    image: redis
