version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        US_ID: $US_ID
        GR_ID: $GR_ID
    image: bilbo-rails_app:latest
    #command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home/bilbo/app
    env_file:
      - .env
    ports:
      - "80:3000"
      - "81:80"
    depends_on:
      - db

  sidekiq:
    image: bilbo-rails_app:latest
    #command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec sidekiq"
    depends_on:
      - redis
      - db
      - app
    volumes:
      - .:/home/bilbo/app
    env_file:
      - .env
    environment:
      COMPONENT: sidekiq

  adminer:
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379

  # elasticsearch:
  #   image: elasticsearch:6.4.2
  #   ports:
  #     - 9200:9200
  #   environment:
  #     - discovery.type=single-node

volumes:
  postgres-volume:
