default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "dbpass" }%>
  variables:
    statement_timeout: 20000

development:
  <<: *default
  database: bilbo_development


test:
  <<: *default
  database: bilbo_test%

staging:
  <<: *default
  database: bilbo_staging

demo:
  <<: *default
  database: bilbo_demo


production:
  <<: *default
  database: bilbo
