clean_temp_files:
  cron: "*/30 * * * *"
  class: "CleanTempFilesWorker"
monthly_provider_report:
  cron: "0 10 26 * *"
  class: "MonthlyProviderReportWorker"
update_board_offset:
  cron: "0 1 * * *"
  class: "UpdateBoardOffsetWorker"
update_remaining_impressions:
  cron: "0 0 * * *"
  class: "UpdateRemainingImpressionsWorker"
