clean_temp_files:
  cron: "*/30 * * * *"
  class: "CleanTempFilesWorker"
monthly_provider_report:
  cron: "0 10 26 * *"
  class: "MonthlyProviderReportWorker"
sidekiq_heartbeat:
  cron: "*/2 * * * *"
  class: "SidekiqHeartbeatWorker"
update_board_offset:
  cron: "5 2 * * *"
  class: "UpdateBoardOffsetWorker"
monitor_impressions:
  cron: "0 12 * * *"
  class: "MonitorImpressionsWorker"
monitor_campaigns:
  cron: "0 0,4,8,12,16,20 * * *"
  class: "MonitorCampaignsWorker"
witness_days_verification_worker:
  cron: "0 12 * * *"
  class: "WitnessDaysVerificationWorker"
generate_sitemap_job:
  cron: "0 1 * * *"
  class: "RegenerateSitemapWorker"
