clean_temp_files:
  cron: "*/30 * * * *"
  class: "CleanTempFilesWorker"
monthly_provider_report:
  cron: "0 10 26 * *"
  class: "MonthlyProviderReportWorker"
sidekiq_heartbeat:
  cron: "*/2 * * * *"
  class: "SidekiqHeartbeatWorker"
update_board_offset:
  cron: "5 2 * * *"
  class: "UpdateBoardOffsetWorker"
monitor_impressions:
  cron: "0 12 * * *"
  class: "MonitorImpressionsWorker"
witness_days_verification_worker:
  cron: "0 12 * * *"
  class: "WitnessDaysVerificationWorker"
